@localhost=localhost:4004/odata/v4/main
@productId=a8a1b439-ed0c-4910-8a2a-e4294dabbe54

GET http://{{localhost}}/Products
Content-Type: application/json

###

POST  http://{{localhost}}/Products
Content-Type: application/json

{
    "id": "{{productId}}",
    "name": "mouse",
    "price": 1
}

###

DELETE http://{{localhost}}/Products(id={{productId}})
Content-Type: application/json



