@localhost=localhost:4004/odata/v4/main
@id=a527b1dc-3491-4c3b-a61b-d4b253cd3b86
@customerId=92482150-ae73-4d28-839d-eee90c96ab63
@productId1=73640951-af56-4d5d-8f55-7493d3d638a8 
# produto sem estoque
@productId2=1113638d-9959-4ab4-b01c-b46097764a12

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345


{
    "id": "{{id}}",
    "customer_id": "14868955-f250-4562-a6e9-86134e393855",
    "items": [
        {
           "id": "cb1a6311-0ecc-4e07-9b95-d7f7cbc57eb7",
           "header_id": "{{id}}",
           "product_id": "{{productId2}}",
           "quantity": 10,
           "price": 2.99
        },
        {
           "id": "036d6c48-2309-476a-9314-00beb1c122e5",
           "header_id": "{{id}}",
           "product_id": "{{productId2}}",
           "quantity": 5,
           "price": 1.33
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345
{}



###

#Teste de busca com filter

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 36.55
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345


###

#Teste 1) Expandindo os items

GET http://{{localhost}}/SalesOrderHeaders?$expand=items, customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

####

#Teste 1) Expandindo os items

GET http://{{localhost}}/SalesOrderHeaders?$expand=items($expand=product;$filter=quantity eq 10), customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

#Selecionar somente e id do sales order header

GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer_id&$filter=customer_id eq 92482150-ae73-4d28-839d-eee90c96ab63&$expand=customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345
###

# Descobrindo a quantidade de registros.

GET http://{{localhost}}/SalesOrderHeaders?$skip=3&$top=3
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

# Buscando dados com o search

GET http://{{localhost}}/SalesOrderHeaders?$search=ano&$expand=customer
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

